version: '3'
services:

 postgresdb:
   image: postgres:latest
   container_name: postgresdb
   environment:
     POSTGRES_DB: skunksdb
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: 1
   volumes:
   - dbdata:/pgdb


 mariadb:
   build:
     context: .
     dockerfile: docker/db/Dockerfile
   container_name: mariadb
   environment:
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_DATABASE=skunksdb
      - MYSQL_USERNAME=admin
      - MYSQL_PASSWORD=1
      - MYSQL_INITDB_SKIP_TZINFO=1
   ports:
     - 3306:3306
   volumes:
   - dbdata:/mdb
   tty: true


 app:
  build:
    context: .
    dockerfile: docker/web/Dockerfile
  container_name: skunksapp
  depends_on:
    - postgresdb
    - mariadb
  ports:
    - 80:9000
  volumes:
    - appdata:/app

volumes:
  appdata:
  dbdata: